inherit_from: .rubocop_todo.yml

# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

# Exclude .html.erb files from linting as RuboCop does not handle ERB syntax
AllCops:
  Exclude:
    - '**/*.html.erb'

# ===========================
# Project-specific rules here
# Uncomment and adjust as needed
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
#
# Metrics/BlockLength:
#   Max: 30
#
# Naming/VariableName:
#   Enabled: true
#
# Lint/UselessAssignment:
#   Enabled: true
# ===========================
