default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode

development:
  prepared_statements: false
  url: <%= ENV["DATABASE_URL_DEVELOPMENT"] %>

test:
  prepared_statements: false
  url: <%= ENV["NEW_DATABASE_URL"] %>

production:
  url: <%= ENV["DATABASE_URL_PRODUCTION"] %>
